
/*
#####  
   */
// action types for fetching files
const FILES_ACTIONS = {
    FETCH_FILES: 'APP/SRC/FEATURES/GALLERYVIEWER/CONSTANTS/FETCH_FILES',
    ADD_FETCH: 'APP/SRC/FEATURES/GALLERYVIEWER/CONSTANTS/ADD_FETCH'
}

/*
#####  
   */
// action constants type for 'selected files'

const SELECTED_FILE_ACTIONS = {
    SELECTED_FILE: 'APP/SRC/FEATURES/GALLERYVIEWER/CONSTANTS/SELECTED_FILE',
    UNSELECT_FILE: 'APP/SRC/FEATURES/GALLERYVIEWER/CONSTANTS/UNSELECT_FILE'
}


export const ACTION_TYPE = {
    FILES_ACTIONS,
    SELECTED_FILE_ACTIONS
}
